### PR TITLE
added target for external links on index

### PR DESCRIPTION
**Pull request by GiffenGood1**

### CODE REVIEW

**Review by rmklaus12 — CHANGES_REQUESTED** [review]
No! We do not allow target="_blank", please remove

**Comment by GiffenGood1** [comment]
ok

**Comment by rmklaus12** [comment]
@GiffenGood1 Thank you for reverting these changes but need you to rebase and clean up the commits

**Comment by rmklaus12** [comment]
@GiffenGood1 Good one! This is now an odd one because it shows no files changed. But hopefully a good exercise for you

**Pull request merged**
