### PR TITLE
Update navbar links and hover style

### PR DESCRIPTION
**Pull request by vizpal**
This PR has updates to the following files.

**_contributors_page.html_**
_+ Update link for About page_
_+ Update link for Home page_
_+ Update link for Contributors page_
_+ Update stylesheet link to pickup correct stylesheet__

**_about.html_**
_+ Add navbar and stylesheet to maintain same feel for all pages_

**_style.css_**
_+ Add hover effect to text in navbar._ 

------------------------------------------------------------

Very happy with this PR... 
Website has started take shape..
... more work to be done !

### CODE REVIEW

**Comment by vizpal** [comment]
I am on Windows and have been using chrome for testing out the behavior.

The updates with `font-weight` looks very subtle to me after you mentioned that...
Anyways, I did some trials and following are alternate solutions to the problem.

Navbar

In my opinion, I like Variation #1 from the above image as it just inverted the colors and makes it more readable.

@rmklaus12 Did you have any color scheme in mind ? 
Do let me know your feedback...

Will make necessary changes based on your feedback..

Cheers!

**Comment by rmklaus12** [comment]
Awesome @vizpal! I thought it might be subtle, but I couldn't see a change at all on Chrome and Mac. I like variation #1 as well, as it sticks to the overall theme the best. Go for it!

**Comment by vizpal** [comment]
@rmklaus12 Updates have been pushed to the branch..

**Comment by rmklaus12** [comment]
This looks great, thank you @vizpal!

**Pull request merged**
